// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWkk8ycDF6wa-bsMpzYEv4D-85QUv8vk8',
    appId: '1:912018791389:ios:5a40bc1684bd5a3c803434',
    messagingSenderId: '912018791389',
    projectId: 'yetnew-home-device',
    storageBucket: 'yetnew-home-device.firebasestorage.app',
    iosBundleId: 'com.example.yetnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWkk8ycDF6wa-bsMpzYEv4D-85QUv8vk8',
    appId: '1:912018791389:ios:5a40bc1684bd5a3c803434',
    messagingSenderId: '912018791389',
    projectId: 'yetnew-home-device',
    storageBucket: 'yetnew-home-device.firebasestorage.app',
    iosBundleId: 'com.example.yetnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJ3ctcM5MSFquTlSr-PnVWi3pr0VlvHY',
    appId: '1:912018791389:web:03b82b303e621fe2803434',
    messagingSenderId: '912018791389',
    projectId: 'yetnew-home-device',
    authDomain: 'yetnew-home-device.firebaseapp.com',
    storageBucket: 'yetnew-home-device.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJ3ctcM5MSFquTlSr-PnVWi3pr0VlvHY',
    appId: '1:912018791389:web:03b82b303e621fe2803434',
    messagingSenderId: '912018791389',
    projectId: 'yetnew-home-device',
    authDomain: 'yetnew-home-device.firebaseapp.com',
    storageBucket: 'yetnew-home-device.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpl23XDkxt3b_ccbPetUg_NzrsA7YXoc',
    appId: '1:912018791389:android:a2fc911869ed1e37803434',
    messagingSenderId: '912018791389',
    projectId: 'yetnew-home-device',
    storageBucket: 'yetnew-home-device.firebasestorage.app',
  );

}